apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metalstack.fullname" . }}-backend-secret
  namespace: {{ include "metalstack.namespace" . }}
  labels:
    {{- include "metalstack.backend.labels" . | nindent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{ .Values.backend.secrets.datasourceUrl | b64enc | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.secrets.datasourceUsername | b64enc | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.secrets.datasourcePassword | b64enc | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.backend.secrets.keycloakIssuerUri | b64enc | quote }}
  KEYCLOAK_JWK_URI: {{ .Values.backend.secrets.keycloakJwkUri | b64enc | quote }}
  MAIL_HOST: {{ .Values.backend.secrets.mailHost | b64enc | quote }}
  MAIL_PORT: {{ .Values.backend.secrets.mailPort | b64enc | quote }}
  MAIL_USERNAME: {{ .Values.backend.secrets.mailUsername | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.backend.secrets.mailPassword | b64enc | quote }}
