apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metalstack.fullname" . }}-frontend-config
  namespace: {{ include "metalstack.namespace" . }}
  labels:
    {{- include "metalstack.frontend.labels" . | nindent 4 }}
data:
  BACKEND_SERVICE_NAME: {{ .Values.frontend.config.backendServiceName | quote }}
  BACKEND_SERVICE_PORT: {{ .Values.frontend.config.backendServicePort | quote }}
