{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metalstack.fullname" . }}-postgres-secret
  namespace: {{ include "metalstack.namespace" . }}
  labels:
    {{- include "metalstack.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgres.secrets.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.secrets.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.password | b64enc | quote }}
{{- end }}
